name: "Run basic tasks"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
    build:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout the repo
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: 20.x

        - name: Install Dependancies
          run: npm install

        - name: Run lint
          run: npm run lint

        - name: Run tests
          run: npm run test

        - name: Run Build
          run: npm run build



